//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.17 at 05:30:16 PM IST 
//


package com.gp.cybersource.common.stub;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecisionReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionReply"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="casePriority" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="activeProfileReply" type="{urn:schemas-cybersource-com:transaction-data-1.104}ProfileReply" minOccurs="0"/&gt;
 *         &lt;element name="velocityInfoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionReply", propOrder = {
    "casePriority",
    "activeProfileReply",
    "velocityInfoCode"
})
public class DecisionReply {

    protected BigInteger casePriority;
    protected ProfileReply activeProfileReply;
    protected String velocityInfoCode;

    /**
     * Gets the value of the casePriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCasePriority() {
        return casePriority;
    }

    /**
     * Sets the value of the casePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCasePriority(BigInteger value) {
        this.casePriority = value;
    }

    /**
     * Gets the value of the activeProfileReply property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileReply }
     *     
     */
    public ProfileReply getActiveProfileReply() {
        return activeProfileReply;
    }

    /**
     * Sets the value of the activeProfileReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileReply }
     *     
     */
    public void setActiveProfileReply(ProfileReply value) {
        this.activeProfileReply = value;
    }

    /**
     * Gets the value of the velocityInfoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVelocityInfoCode() {
        return velocityInfoCode;
    }

    /**
     * Sets the value of the velocityInfoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVelocityInfoCode(String value) {
        this.velocityInfoCode = value;
    }

}
